baseURL = 'https://acapio.de/'
languageCode = 'de'
title = 'Acapio.de'


theme = "hugo-clarity"
DefaultContentLanguage = "de"

[taxonomy]
name = "Andy"


[params]
enableSearch = true
twitter = "@PrangerInfo"
numberOfTagsShown = 14
logo = "logo.webp"
iconsDir = "icons/"
mainSections = ["posts"]
section = "posts"
usePageBundles = false
description = 'Datenschutz, Datensicherheit, Schutz vor Scam, Phishing mit einer Prise Humor'
keywords = ["security", "spam protection", "datensicherheit", "phishing", "scam"] # Set your site's meta tag (SEO) keywords here. Alternatively set these in your home page content file e.g. content/_index.md. Whatever is set in the latter will take precedence.
enforceLightMode = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 10


[menus]
[[menus.main]]
  name = "Home"
  url = "/"
  weight = -100

[[menus.main]]
  name = "Über"
  url = "/about/"
  weight = -90

[[menus.main]]
  name = "Datenschutz"
  url = "/datenschutz/"
  weight = -80

[[menus.main]]
  name = "Impressum"
  url = "/impressum/"
  weight = -1


[goldmark]
  [goldmark.renderer]
    hardWraps = false
    unsafe = true # change to false to disable inclusion of rawHTML and math functions
    xhtml = false
  [goldmark.extensions]
    typographer = false
  [highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will
    noClasses = false
    # style = "monokai"
    tabWidth = 2